### ISSUE TITLE
SwingJS java.util.Regex doesn't support "(?s)" to enable DOT_ALL mode

### ISSUE THREAD

**Issue by foreveremain** [BobHanson/java2script#169]
Compiling a pattern containing (?s) should enable DOT_ALL mode for java.util.Regex:

`
private static Pattern FIND_ANY_PATTERN = Pattern.compile("(?s).*");
`

 this is enabled in JS with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll#:~:text=The%20dotAll%20property%20indicates%20whether,an%20individual%20regular%20expression%20instance.

**Comment by foreveremain** [comment]
I'd attempt a patch myself, but I can't see the original java/util/Regex.java code at https://github.com/BobHanson/java2script/tree/master/sources/net.sf.j2s.java.core/src/java/util/regex  - instead there's what seem to be j2s generated JS files.

**Comment by BobHanson** [comment]
SwingJS does not use java.util.regex. It uses JavaScript RegExp. There are a few places in SwingJS where the Java code is not used. java.util.regex is one. I cannot remember why, though. Probably because the original version of Java2Script had a completely JavaScript version of this package. But it would be a fine idea for me to get the Java back in for Pattern and Matcher. It's certainly a hassle to have that like that. Do look to see if Scanner code could be adjusted to not use that particular pattern. What exactly does (?s) do?

**Comment by BobHanson** [comment]
A full rewrite of java.util.regex.Pattern and Matcher, with integration into String class methods. 

- adds (?x) pattern prefix processing where x= i m s u 
- redesigned from Java 8 JDK; includes streams (untested)
- does not support access to source pointers for start/end of groups, though actual result group substrings are are discoverable. JavaScript just does not provide a mapping of individual groups to start/end positions.
