### ISSUE TITLE
SimpleHttpClient ignores HTTP status code

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#183]
SimpleHttpClient seems to completely ignore the HTTP status code, returning 200 for all successful (<400) and 404 for unsuccessful (>=400) requests regardless of an actual code received from the server.

**Comment by warownia1** [comment]
@BobHanson can you look at it, it's quite important for REST clients to have correct status code. The issue seems to be on the javascript side as SimpleHttpClient works correctly in java.

**Comment by BobHanson** [comment]
Should be fixed and pulled all the way through to java2script/java2script. See test/Test_HTTP.java returning correct 202 status code. 

Testing async
https://www.compbio.dundee.ac.uk/slivka/api/services/example
Testing async...submitted...
Testing async...returned:
{
"statuscode": 202,
"uuid": "IWpVBCwrTSiOUI5LgwOvxg",
"URI": "/slivka/api/tasks/IWpVBCwrTSiOUI5LgwOvxg"
}
202

**Comment by BobHanson** [comment]
this issue is ready for testing. New SwingJS-site.zip

Note that JavaScript AJAX cannot distinguish among 400-499 codes, returning only "NetworkError" and setting the SimpleHttpClient response to 400 in all case. (Requested PUT to slivka in Java will report status=405.)

test.Test_HTTP.java should display the following in System.out


testApplet running test.Test_HTTP
Running main(args) in class test.Test_HTTP
Testing sync GET
https://www.compbio.dundee.ac.uk/slivka/api/services
SimpleHttpClient GET state=200 uri=https://www.compbio.dundee.ac.uk/slivka/api/services
{ "statuscode": 200, "services": ... }
Testing async GET
async GET submitted...
Testing sync POST
https://www.compbio.dundee.ac.uk/slivka/api/services/example
SimpleHttpClient POST state=202 uri=https://www.compbio.dundee.ac.uk/slivka/api/services/example
{ "statuscode": 202, "uuid": "wUIIIXFTTlSfAM7EHdfzTA", "URI": "/slivka/api/tasks/wUIIIXFTTlSfAM7EHdfzTA" }
Testing sync PUT
https://www.compbio.dundee.ac.uk/slivka/api/services/example
SimpleHttpClient PUT state=400 uri=https://www.compbio.dundee.ac.uk/slivka/api/services/example
Testing async PUT, reuse of req
async PUT submitted...
async GET returned SUCCESS:
SimpleHttpClient GET state=200 uri=https://www.compbio.dundee.ac.uk/slivka/api/services
{ "statuscode": 200, "services":  ... }
async PUT returned FAILED: java.net.UnknownHostException: https://www.compbio.dundee.ac.uk/slivka/api/services/example
SimpleHttpClient PUT state=400 uri=https://www.compbio.dundee.ac.uk/slivka/api/services/example

**Comment by warownia1** [comment]
> Note that JavaScript AJAX cannot distinguish among 400-499 codes

Are you sure? 
`$.get("http://httpstat.us/405").fail(function(jqxhr) { console.log(jqxhr.status); });`
reports 405 as it should be.

**Comment by BobHanson** [comment]
It is working now. See test.Test_HTML.java  

The problem was that J2S.addDirectDatabaseCall() had not been issued, so it was working through the https://chemapps relay. 




	static {
		/** @j2sNative 
		J2S.addDirectDatabaseCall("www.compbio.dundee.ac.uk/slivka");
		
		J2S.addDirectDatabaseCall("httpstat.us");

		 */

	}

**Comment by BobHanson** [comment]
Working now. 

		try {
			URL url = new URL("http://httpstat.us/405");
			HttpURLConnection c = (HttpURLConnection) url.openConnection();
			int code = c.getResponseCode();
			System.out.println("httpstat.us reports " + code);
			InputStream oi = url.openStream();
			String s = new String(oi.readAllBytes());
			System.out.println("httpstat.us reports " + s);
		} catch (IOException e) {
			System.out.println(e);
		}



testApplet running test.Test_HTTP
Running main(args) in class test.Test_HTTP
Testing httpstat 405
httpstat.us reports 405

**Comment by BobHanson** [comment]
Java still reports 403:

Testing httpstat 405
httpstat.us reports 403
java.io.IOException: Server returned HTTP response code: 403 for URL: http://httpstat.us/405


And this is better now in JavaScript:

Running main(args) in class test.Test_HTTP
Testing httpstat 405
httpstat.us reports 405
java.io.IOException: Server returned HTTP response code: 405 for URL: http://httpstat.us/405

**Comment by BobHanson** [comment]
Once you have checked this, I will close it.
