### ISSUE TITLE
Incorrect returns of start and end methods of Matcher from the regex library.

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#253]
According to the documentation, the method `start(int)` (or `end(int)`) should return the start (end) index of the captured group or -1 if the match was successful, but the group did not match. With capturing group 0 denoting the entire pattern,
the expressions `m.start()` and `m.start(0)` (or `m.end()` and `m.end(0)`) are equivalent. Java2script implementation of the Matcher returns -1 for the start and the end of group 0 despite a successful match.

Example:
```java
String lipsum = "Lorem ipsum dolor sit amet";
Pattern pattern = Pattern.compile("ipsum");
Matcher m = pattern.matcher(lipsum);
m.find();
int start = m.start();
int end = m.end();
int start0 = m.start(0);
int end0 = m.end(0);
System.out.format("%d %d%n", start, end);
System.out.format("%d %d%n", start0, end0);
```
The code outputs _6 11_ twice in java, but it outputs _6 11_ and _-1 -1_ in javascript.

**Comment by BobHanson** [comment]
Sorry to say that JavaScript does not provide start/end capabilities with its RegEx implementation. From 

https://github.com/BobHanson/java2script/raw/master/sources/net.sf.j2s.java.core/doc/Differences.txt

_Formatter/Regex limitations
---------------------------

Some browsers cannot process Regex "look-behind" process such as (?<=\W)
java.util.regex.Matcher and Pattern use JavaScript's RegExp object rather than
the native Java object. These are not identical. Only flags /igm are supported.
**Matcher.start(groupID) is not supported.**_

**Comment by BobHanson** [comment]
But I have an idea....

**Comment by BobHanson** [comment]
The issue was that JavaScript's RegEx does not allow access to the start/end positions of the match, just the match string itself. By adding specially named groups to every text node, we can trace the exact position of the other groups. In the end, the specially named groups are skipped, and only the user-defined groups are left. Tested using test.Test_Regex
